# Generated by Django 5.1.4 on 2025-01-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayback',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='gameplayback',
            name='spotify_uri',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
