# Generated by Django 5.1.4 on 2025-01-30 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify_games', '0002_remove_gameplayback_preview_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamestate',
            name='current_state',
            field=models.JSONField(default=dict),
        ),
    ]
