"""
Django settings for silleyBEnd project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta
import base64
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

AUTH_USER_MODEL = 'spotify.User'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-jaz1e_hp19!pbp)x8rat!6l5*z%a-bogf+gq)u^ix0+2xmb(7w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}

GAME_CACHE_TIMEOUT = 3600  # 1 hour

# Session cache settings (optional)
SESSION_CACHE_ALIAS = "default"
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"  # Use cache for better performance


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'spotify',
    'channels',
    'spotify_games',
    'rest_framework',
    'corsheaders',
    'django_extensions',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'spotify.middleware.SpotifyTokenMiddleware',
    'spotify_games.middleware.JWTTokenRefreshMiddleware',
]

ROOT_URLCONF = 'silleyBEnd.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR,'templates'),
            os.path.join(BASE_DIR,'spotify_games', 'templates'),
            os.path.join(BASE_DIR,'spotify', 'templates'),
            ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Add custom context processor
                #'spotify_games.context_processors.game_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'silleyBEnd.wsgi.application'

ASGI_APPLICATION = 'silleyBEnd.asgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'silley_ops_db',  # Database name
        'USER': 'silley_user',    # Username
        'PASSWORD': 'secure_password',  # Password
        'HOST': 'localhost',      # Database host
        'PORT': '5432',           # Database port (default for PostgreSQL)
    }
}

if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Lagos'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR , 'static'),
    ]

# WhiteNoise configuration
WHITENOISE_USE_FINDERS = True
if not DEBUG:
    WHITENOISE_AUTOREFRESH = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

from decouple import config

SPOTIFY_CLIENT_ID = config("SPOTIFY_CLIENT_ID")
SPOTIFY_CLIENT_SECRET = config("SPOTIFY_CLIENT_SECRET")
SPOTIFY_REDIRECT_URI = config("SPOTIFY_REDIRECT_URI")
DISCOGS_TOKEN = config("YOUR_DISCOG_TOKEN")
DISCOGS_CONSUMER_KEY =  config("CONSUMER_KEY")
DISCOGS_CONSUMER_SECRET = config("CONSUMER_SECRET")
DISCOGS_ACCESS_TOKEN = config("ACCESS_TKEN")
DISCOGS_ACCESS_TOKEN_SECRET = config("ACCESS_TKEN_SECRET")
LASTFM_API_KEY = config("API_KEY")
GENIUS_API_TOKEN = config("GENIUS_API_TOKEN")
OPENAI_API_KEY = config("OPENAI_API_KEY")
TOGETHER_API_KEY = config("TOGETHER_API_KEY")
HUGGINGFACE_API_KEY = config("HUGGINGFACE_API_KEY")
PALM_API_KEY = config("PALM_API_KEY")
SPOTIFY_AUTH_HEADER = f"Basic {base64.b64encode(f'{SPOTIFY_CLIENT_ID}:{SPOTIFY_CLIENT_SECRET}'.encode()).decode()}"

LOGGING = {
    "version": 1,  # Logging configuration version
    "disable_existing_loggers": False,  # Don't disable existing loggers
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {message}",
            "style": "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "DEBUG",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "django_warning.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "spotify_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "spotify.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
        "spotify_games_file": {
            "level": "DEBUG",
            "class": "logging.handlers.RotatingFileHandler",
            "filename": os.path.join(BASE_DIR, "spotify_games.log"),
            "maxBytes": 1024 * 1024 * 5,  # 5 MB
            "backupCount": 5,
            "formatter": "verbose",
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console", "file"],
            "level": "DEBUG",
            "propagate": True,
        },
        "spotify": {  # Custom logger for the spotify app
            "handlers": ["spotify_file","file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "spotify_games": {  # Custom logger for the spotify_games app
            "handlers": ["spotify_games_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# For production, specify allowed origins
CORS_ALLOWED_ORIGINS = [
     "http://localhost:5173", # Your React dev server
    "http://127.0.0.1:5173" ,   
 ]

# During development
 #CORS_ALLOW_ALL_ORIGINS = True # Only for development
CORS_ALLOW_CREDENTIALS = False

#CORS_EXPOSE_HEADERS = ['Content-Type', 'X-CSRFToken']
CORS_EXPOSE_HEADERS = ['Content-Type', 'Authorization']
CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "user-agent",
    "x-requested-with",
]


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}
    
# Session Configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'  # Use database-backed sessions
SESSION_COOKIE_AGE = 1209600  # 2 weeks in seconds
SESSION_COOKIE_SECURE = not DEBUG  # Use secure cookies in production, # Set to False in development if not using HTTPS
SESSION_COOKIE_HTTPONLY = True  # Prevent JavaScript access to session cookie
SESSION_COOKIE_SAMESITE = 'Lax'  # Protect against CSRF
#SESSION_COOKIE_DOMAIN = 'http://127.0.0.1' # Set to your domain in production
SESSION_COOKIE_DOMAIN = None
CSRF_COOKIE_SECURE = not DEBUG   # Set to False in development if not using HTTPS
CSRF_COOKIE_SAMESITE = 'Lax'

# For development
if DEBUG:
    SESSION_COOKIE_SECURE = False  # Allow non-HTTPS in development
    CSRF_COOKIE_SECURE = False




REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'spotify.authentication.JWTAuthentication',
        'spotify_games.authentication.JWTAuthentication',  
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# from django.core.management.utils import get_random_secret_key

# SECRET_KEY = get_random_secret_key()
# JWT_SECRET_KEY = SECRET_KEY  # Use the same or a different key for JWT
