# Generated by Django 5.1.4 on 2025-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_alter_mostlistenedsongs_genres'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostlistenedsongs',
            old_name='duration_ms',
            new_name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='danceability',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='key',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='loudness',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='tempo',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='valence',
        ),
        migrations.AddField(
            model_name='mostlistenedalbum',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='mostlistenedsongs',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
