# Generated by Django 5.1.4 on 2025-01-07 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0004_user_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalTopTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('genres', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('release_date', models.DateField()),
                ('popularity', models.IntegerField(default=0)),
                ('rank', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='TopTracksCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spotify_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('genres', models.TextField(blank=True, null=True)),
                ('duration_seconds', models.IntegerField()),
                ('release_date', models.DateField(blank=True, null=True)),
                ('popularity', models.IntegerField(default=0)),
                ('country_code', models.CharField(max_length=2)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='debut_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='gender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='members',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='most_popular_song',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='num_albums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='RelatedArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_artist_id', models.CharField(max_length=255)),
                ('related_artist_name', models.CharField(max_length=255)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_artists', to='spotify.mostlistenedartist')),
            ],
        ),
    ]
