# Generated by Django 5.1.4 on 2025-01-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0006_remove_mostlistenedalbum_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostlistenedalbum',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedsongs',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
