# Generated by Django 5.1.4 on 2025-01-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0007_mostlistenedalbum_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltoptracks',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='mostlistenedalbum',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='mostlistenedartist',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='last_updated',
        ),
        migrations.RemoveField(
            model_name='toptrackscountry',
            name='last_updated',
        ),
    ]
