# Generated by Django 5.1.4 on 2025-01-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0008_remove_globaltoptracks_last_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalTopTracks',
        ),
        migrations.RemoveField(
            model_name='relatedartist',
            name='artist',
        ),
        migrations.DeleteModel(
            name='TopTracksCountry',
        ),
        migrations.DeleteModel(
            name='RelatedArtist',
        ),
    ]
