# Generated by Django 5.1.4 on 2025-01-09 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0009_delete_globaltoptracks_remove_relatedartist_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostlistenedalbum',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.CreateModel(
            name='GlobalTopSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('explicit', models.BooleanField(default=False)),
                ('listeners', models.IntegerField(default=0)),
                ('playcount', models.IntegerField(default=0)),
                ('album', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.user')),
            ],
        ),
        migrations.CreateModel(
            name='TopGenreSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unknown', max_length=255)),
                ('artists', models.CharField(max_length=255)),
                ('explicit', models.BooleanField(default=False)),
                ('listeners', models.IntegerField(default=0)),
                ('playcount', models.IntegerField(default=0)),
                ('album', models.CharField(max_length=255)),
                ('duration_seconds', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spotify.user')),
            ],
        ),
    ]
