# Generated by Django 5.1.4 on 2025-01-10 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0010_mostlistenedalbum_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaltopsongs',
            name='album',
        ),
        migrations.RemoveField(
            model_name='globaltopsongs',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='globaltopsongs',
            name='explicit',
        ),
        migrations.RemoveField(
            model_name='globaltopsongs',
            name='listeners',
        ),
        migrations.RemoveField(
            model_name='globaltopsongs',
            name='playcount',
        ),
        migrations.RemoveField(
            model_name='topgenresongs',
            name='album',
        ),
        migrations.RemoveField(
            model_name='topgenresongs',
            name='duration_seconds',
        ),
        migrations.RemoveField(
            model_name='topgenresongs',
            name='explicit',
        ),
        migrations.RemoveField(
            model_name='topgenresongs',
            name='listeners',
        ),
        migrations.RemoveField(
            model_name='topgenresongs',
            name='playcount',
        ),
        migrations.AlterField(
            model_name='mostlistenedsongs',
            name='duration_seconds',
            field=models.FloatField(),
        ),
    ]
