# Generated by Django 5.1.4 on 2025-01-13 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0012_alter_globaltopsongs_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topgenresongs',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='topgenresongs',
            name='user',
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedsongs',
            name='lyrics',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='GlobalTopSongs',
        ),
        migrations.DeleteModel(
            name='TopGenreSongs',
        ),
    ]
