# Generated by Django 5.1.4 on 2025-01-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0013_alter_topgenresongs_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostlistenedsongs',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
