# Generated by Django 5.1.4 on 2025-01-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0014_mostlistenedsongs_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='mostlistenedartist',
            name='most_popular_preview_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='most_popular_song_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedsongs',
            name='display_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
