# Generated by Django 5.1.4 on 2025-01-21 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0015_mostlistenedartist_most_popular_preview_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mostlistenedsongs',
            old_name='display_url',
            new_name='preview_url',
        ),
    ]
