# Generated by Django 5.1.4 on 2025-01-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0016_rename_display_url_mostlistenedsongs_preview_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mostlistenedartist',
            name='most_popular_preview_url',
        ),
        migrations.RemoveField(
            model_name='mostlistenedsongs',
            name='preview_url',
        ),
        migrations.AddField(
            model_name='mostlistenedartist',
            name='most_popular_track_uri',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mostlistenedsongs',
            name='track_uri',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
