# Generated by Django 5.1.4 on 2025-02-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0019_alter_spotifytoken_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_data_processed',
            field=models.BooleanField(default=False),
        ),
    ]
