# Generated by Django 5.1.4 on 2025-02-04 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0020_user_is_data_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
